"use client"

import { useState } from 'react';
import Head from 'next/head';
import Modal from '@/components/Modal';
import CustomToast from '@/components/CustomToast';

import Image from 'next/image';
import { Skeleton } from '@mui/material';

export default function Home() {
    const [loaded, setLoaded] = useState(false)

    const products = [
        { name: 'Tea', image: '/path/to/tea-image.png' },
        { name: 'Coffee', image: '/path/to/coffee-image.png' },
        { name: 'Gold', image: '/path/to/gold-image.png' },
        { name: 'Silver', image: '/path/to/silver-image.png' },
        { name: 'Coal', image: '/path/to/coal-image.png' },
        { name: 'Charcoal', image: '/path/to/charcoal-image.png' },
    ];
    const [cartItems, setCartItems] = useState(0);
    const [selectedProducts, setSelectedProducts] = useState([]);
    const [showModal, setShowModal] = useState(false);
    const [showToast, setShowToast] = useState(false);
    const [toastMessage, setToastMessage] = useState('');

    const increaseCartItems = () => setCartItems(cartItems + 1);
    const decreaseCartItems = () => setCartItems(cartItems > 0 ? cartItems - 1 : 0);

    const addToCartItem = (index) => {
        const product = products[index];
        setSelectedProducts([...selectedProducts, product]);
        setToastMessage(`${product.name} added to cart!`);
        setShowToast(true);
        setTimeout(() => {
            setShowToast(false);
        }, 3000); // Hide toast after 3 seconds
    };

    const checkoutCart = () => {
        if (selectedProducts.length === 0) {
            alert('Cart is empty');
        } else {
            setShowModal(true);
        }
    };

    return (
        <div>
            <Head>
                <title>Home Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mx-auto p-6">
                <h1 className="text-3xl font-bold">Good Morning, Ikhsan Assiddiqie</h1>
                <p className="text-lg mt-2 mb-4">Find products for you</p>

                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                    {products.map((product, index) => (
                        <div key={index} className="border rounded-lg shadow-lg overflow-hidden">
                            <Image src={product.image} 
                            alt={product.name} 
                            width={300} 
                            height={200} 
                            className={`${(!loaded) ? 'opacity-0': 'opacity-100'}}`}
                            onLoad={() => setLoaded(true)}
                            />
                            {!loaded && (
                                <Skeleton
                                    sx={{ bgcolor: 'grey.100' }}
                                    variant="rectangular"
                                    width="100%"
                                    height="100%"
                                />
                            )}
                            {/* <div className="bg-blue-500 w-full h-32"></div> */}
                            <div className="p-4">
                                <h3 className="text-lg font-semibold">{product.name}</h3>
                                <button
                                    className="mt-4 w-full bg-black text-white py-2 px-4 rounded"
                                    onClick={() => addToCartItem(index)}
                                >
                                    Add to cart
                                </button>
                            </div>
                        </div>
                    ))}
                </div>

                <Modal showModal={showModal} setShowModal={setShowModal} selectedProducts={selectedProducts} />
                {showToast && <CustomToast message={toastMessage} onDismiss={() => setShowToast(false)} />}

                <div className="mt-8">
                    <p className="text-lg">Items in cart right now: <span className="font-bold">{cartItems} items</span></p>
                    <div className="mt-4 space-x-2">
                        <button
                            onClick={decreaseCartItems}
                            className="bg-black text-white py-2 px-4 rounded">
                            Decrease
                        </button>
                        <button
                            onClick={increaseCartItems}
                            className="bg-black text-white py-2 px-4 rounded">
                            Increase
                        </button>
                        <button className="bg-black text-white py-2 px-4 rounded" onClick={checkoutCart}>Pay</button>
                    </div>
                </div>
            </main>
        </div>
    );
}
